# 📘 NumPy Complete Notes

---

# 🟢 SECTION 1: BEGINNER LEVEL

## 1. What is NumPy?   
**NumPy (Numerical Python)** is the core library for numerical computing in Python.

It provides:
- Fast **n-dimensional arrays**
- Mathematical operations on arrays
- Tools for linear algebra, statistics, and random numbers

### Why NumPy over Python lists?
| Feature | Python List | NumPy Array |
|------|-----------|-------------|
| Speed | Slow | Very fast (C-backed) |
| Memory | High | Low |
| Math ops | Loop needed | Vectorized |
| Shape | Flexible | Fixed, structured |

---

## 2. Installing and Importing NumPy
```python
pip install numpy
```

##### Markdown Tips:
- Change code cell to markdown = esc + m
- change back to code= esc + y


In [76]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [77]:
import numpy as np

##  3. NumPy Arrays (ndarray)
### Creating Arrays

<div align="center">
  <img src="/assets/images/7.png" alt="Alt text" width="200"/>
</div>

<!-- ![Plot](/assets/images/7.png){:style="display:block; margin:auto;"} -->

In [ ]:
arr = np.array([1 ,2 ,3, 4 ,5])
print(arr)

[1 2 3 4 5]


In [79]:
a = np.array([1, 2, 3])
print("First array:", a)

First array: [1 2 3]


### Creating Arrays

<div align="center">
  <img src="/assets/images/8.png" alt="Alt text" width="200"/>
</div>

In [80]:
import numpy as np

In [81]:
arr1 = np.array([1.0,2.0,3.0])
print(arr1)

[1. 2. 3.]


In [82]:
print(arr1.size)

3


In [83]:
print(arr1.dtype)

float64


In [84]:
print(arr1.ndim)

1


In [85]:
print(arr1.shape)

(3,)


In [86]:
b = np.array([[1, 2], [3, 4]])
print("Second array:\n", b)
print(b.shape)
print(b.dtype)

Second array:
 [[1 2]
 [3 4]]
(2, 2)
int64


### Key Properties

<div align="center">
  <img src="/assets/images/7.png" alt="Alt text" width="200"/>
</div>

In [87]:
print("Number of dimensions of array A:", a.ndim)     # 1
print("Size in each dimension of array A:", a.shape)    # (3,)
print("Total elements of array A:", a.size)     # 3
print("Datatype of array A:", a.dtype)    # int64

Number of dimensions of array A: 1
Size in each dimension of array A: (3,)
Total elements of array A: 3
Datatype of array A: int64


## 4. Common Array Creation Functions
In NumPy, if the dtype (data type) argument is not explicitly specified, functions like np.ones(), np.zeros(), and np.empty() use numpy.float64 as the default.

### Zero Matrix 

<div align="center">
  <img src="/assets/images/1.png" alt="Alt text" width="200"/>
</div>


In [88]:
arr= np.zeros((3,4),dtype ='int64')
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [89]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Ones Matrix

<div align="center">
  <img src="/assets/images/2.png" alt="Alt text" width="200"/>
</div>

In [90]:
arr3 = np.ones((2, 3), dtype = 'int64')
print(arr3)

[[1 1 1]
 [1 1 1]]


In [91]:
print(np.ones((2, 4)))
# Check for this
#print(np.ones((2, 4),dtype ='int16'))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 2*2 matrix with all 7 values

<!-- <div align="center">
  <img src="data/2.png" alt="Alt text" width="200"/>
</div> -->

In [92]:
arr4 = np.full((3,4),9)
print(arr4)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [93]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])


### Identity matrix

- This line creates the 3x3 identity matrix by manually defining a nested list of values and using the general np.array() function to convert it into a NumPy array. This achieves the same result as np.eye(3) but without using the specific function designed for identity matrices.

<div align="center">
  <img src="/assets/images/9.png" alt="Alt text" width="200"/>
</div>

In [94]:
# "Same identity matrix but without inbuilt function:"
arr = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr)
print("Dimension:", arr.ndim)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension: 2




- This line of code generates the 3x3 identity matrix but does not assign it to a variable or explicitly print it. In an interactive Python session (like a Jupyter notebook or a basic interpreter), the interpreter automatically displays the result of the unassigned expression.

In [95]:
arr5 = np.eye(2)
print(arr5)

[[1. 0.]
 [0. 1.]]


In [96]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- This line of code generates the 3x3 identity matrix and assigns it to a variable named c. The array is stored in memory but is not displayed until a print(c) or other explicit print statement is executed.

In [97]:
c = np.eye(3)
print(c)
print("Dimensions:", c.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimensions: 2


### arange

- np.arange(start, stop, step): Returns an array with values from start to stop-step, with the specified step.
- Use np.arange() when you know the desired step size and are primarily working with integers. It behaves similarly to Python's built-in range() function.


In [98]:
arr6 = np.arange(1,8,0.5)
print(arr6)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [99]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### linspace

- np.linspace(start, stop, num): Returns an array of num evenly spaced values from start to stop (inclusive by default).
- Use np.linspace() when you know the required number of elements and need the endpoint to be included, or when working with floating-point numbers to avoid potential precision issues. 

In [100]:
print("linspace:",np.linspace(0, 1, num=5))


linspace: [0.   0.25 0.5  0.75 1.  ]


## 5. Data Types (dtype)

Common dtypes:

- int32, int64
- float32, float64
- bool
- complex

In [101]:
print(np.array([1, 2, 3], dtype=np.float32))


[1. 2. 3.]


In [102]:
print(np.array([True, False]))

[ True False]
